[env:bno08x-spi-test]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi
board_build.partitions = default_16MB.csv
upload_port = COM11
monitor_port = COM11
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit BNO08x@^1.2.5
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
